import { BILLING_UI_HTML } from "./billingUI";
import { handleChat } from "./chat";
import { CHAT_UI_HTML } from "./chatUI";
import {
  claimHousehold,
  clearCustomerSessionCookie,
  createCustomerSessionCookie,
  extractCustomerSessionCookie,
  verifyCustomerLogin,
  verifyCustomerSessionCookie,
} from "./customers";
import { DASHBOARD_HTML } from "./dashboardUI";
import { handleEnergyRun, handleEnergyStatus, runAllHeatPumpOptimizations, runSolarAndEvOptimization } from "./energy";
import {
  createHousehold,
  findHouseholdByStripeCustomerId,
  getHouseholdBilling,
  getHouseholdEnergyConfig,
  type HouseholdEnergyConfig,
  householdBelongsToIntegrator,
  listIntegratorHouseholds,
  type OffPeakWindow,
  resolveHousehold,
  setHouseholdEnergyConfig,
  setHouseholdHaConfig,
  setHouseholdPin,
  setHouseholdStripeCustomer,
  setHouseholdSubscription,
  updateSubscriptionAddonsBySubscriptionId,
  updateSubscriptionStatusBySubscriptionId,
  verifyHouseholdPin,
} from "./households";
import {
  clearSessionCookie,
  createIntegrator,
  createSessionCookie,
  extractSessionCookie,
  verifyIntegratorLogin,
  verifySessionCookie,
} from "./integrators";
import { createStripeCustomer, createStripeSubscription, verifyStripeWebhookSignature } from "./stripe";

export interface Env {
  DB: D1Database;
  MEMORY_INDEX: VectorizeIndex;

  // Secrets — set with `wrangler secret put <NAME>`, never in wrangler.jsonc.
  OPENAI_API_KEY: string;
  // The bootstrap/default household's bearer token — see households.ts.
  // Every household added after multi-tenancy (docs/households.md)
  // authenticates via its own row in D1 instead; this one secret only
  // covers the single 'default' household migration 0003 backfilled
  // existing data into.
  ROSE_API_KEY: string;
  // Legacy global Home Assistant connection — only used as a fallback for
  // the bootstrap 'default' household (see households.ts's
  // getHouseholdHaConfig). Every household added since multi-tenancy
  // configures its own HA connection, stored (encrypted) in D1 instead.
  HA_URL?: string;
  HA_TOKEN?: string;
  // Optional — enables the web_search tool (see search.ts) when set. Absent,
  // ROSE just doesn't offer that tool and answers from what it already knows.
  BRAVE_SEARCH_API_KEY?: string;
  // 32 random bytes as 64 hex chars — encrypts/decrypts each household's own
  // Home Assistant token at rest (crypto.ts's encryptSecret/decryptSecret).
  // Generate with `openssl rand -hex 32`. Required before any
  // integrator-managed household can configure its own HA connection;
  // households.ts's setHouseholdHaConfig throws without it.
  ENCRYPTION_KEY?: string;
  // 32 random bytes as 64 hex chars — signs both integrator (integrators.ts)
  // and customer-portal (customers.ts) session cookies. Generate with
  // `openssl rand -hex 32`. Required for any /integrator/* or /portal/*
  // route to work at all.
  SESSION_SECRET: string;

  // Billing (Stripe) — see docs/billing.md. All optional; /portal/* routes
  // that need Stripe fail with a clear 500 if any of these are missing
  // rather than an unhandled exception, same pattern as SESSION_SECRET
  // above. A household with no subscription (the default for every
  // household today) is entirely unaffected either way.
  STRIPE_SECRET_KEY?: string; // sk_test_... / sk_live_... — never logged, never returned to a client
  // Two separate recurring Price objects — the base assistant subscription
  // and the heating optimization add-on (docs/billing.md) — rather than one
  // flat price, so a household can subscribe to either or both. A
  // household's subscription carries one or both as line items; the
  // webhook (handleBillingWebhook) inspects which and keeps
  // heating_addon_active in sync.
  STRIPE_CHAT_PRICE_ID?: string; // price_...
  STRIPE_HEATING_PRICE_ID?: string; // price_...
  // Not actually secret — Stripe's publishable keys are designed to ship in
  // client-side JS (see billingUI.ts). Kept here rather than hardcoded so
  // it can be rotated without a redeploy, and kept out of wrangler.jsonc's
  // vars anyway since it's still account-specific config, not a default.
  STRIPE_PUBLISHABLE_KEY?: string; // pk_test_... / pk_live_...
  // Verifies POST /billing/webhook deliveries actually came from Stripe
  // (stripe.ts's verifyStripeWebhookSignature) — generated by Stripe once
  // the webhook endpoint is registered in its dashboard, not something you
  // choose yourself like the others above.
  STRIPE_WEBHOOK_SECRET?: string; // whsec_...

  // Plain vars, safe to keep in wrangler.jsonc.
  OPENAI_CHAT_MODEL: string;
  OPENAI_EMBEDDING_MODEL: string;

  // Energy optimization — see docs/energy.md. A global kill switch plus two
  // account-level (not per-household) config values that stay here:
  // MET_OFFICE_API_KEY is Brandon's own developer account, and
  // OCTOPUS_PRODUCT_CODE is a national tariff code override, not something
  // that varies per home. Everything that IS home-specific — heat pump
  // entity ids, temperature band, Octopus region, forecast location — moved
  // to per-household D1 columns in migration 0008 (see households.ts's
  // HouseholdEnergyConfig) once heating optimization became a billed
  // per-household add-on rather than a single-Worker global feature.
  ENERGY_OPTIMIZATION_ENABLED?: string; // "true" to enable; anything else (including unset) is off
  OCTOPUS_PRODUCT_CODE?: string; // optional override; auto-detected if unset
  MET_OFFICE_API_KEY?: string;

  // Solar (SolarEdge) + EV charging — still single-tenant/global (not sold
  // as a billed add-on yet, unlike heat pump optimization above), scoped to
  // the bootstrap 'default' household's Home Assistant connection. A live
  // solar surplus reading, if configured, starts EV charging.
  SOLAREDGE_API_KEY?: string;
  SOLAREDGE_SITE_ID?: string;
  // Controlled via Home Assistant, not a direct SolarEdge call — see
  // docs/energy.md for why. *_SERVICE values are "domain.service" strings,
  // e.g. "switch.turn_on" — whatever your HA integration for the charger
  // exposes.
  ROSE_EV_CHARGER_ENTITY_ID?: string;
  ROSE_EV_CHARGER_START_SERVICE?: string;
  ROSE_EV_CHARGER_STOP_SERVICE?: string;
  ROSE_EV_CHARGER_SURPLUS_THRESHOLD_KW?: string; // default 1.4 if unset
}

// Permissive CORS: this API is protected by its own bearer-token check
// (resolveHousehold below), not by same-origin/cookie assumptions, so
// allowing any origin doesn't weaken that — it just lets a browser-based
// client (e.g. a standalone chat page) call this API directly, which the
// Cloudflare Workers runtime doesn't allow by default.
const CORS_HEADERS: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "authorization, content-type",
};

function withCors(response: Response): Response {
  const headers = new Headers(response.headers);
  for (const [key, value] of Object.entries(CORS_HEADERS)) {
    headers.set(key, value);
  }
  return new Response(response.body, { status: response.status, headers });
}

const JSON_HEADERS = { "content-type": "application/json" };

function unauthorized(): Response {
  return new Response(JSON.stringify({ error: "unauthorized" }), { status: 401, headers: JSON_HEADERS });
}

function jsonError(message: string, status: number): Response {
  return new Response(JSON.stringify({ error: message }), { status, headers: JSON_HEADERS });
}

function jsonOk(body: Record<string, unknown>, extraHeaders?: Record<string, string>): Response {
  return new Response(JSON.stringify(body), { headers: { ...JSON_HEADERS, ...extraHeaders } });
}

function extractBearerToken(request: Request): string | null {
  const auth = request.headers.get("authorization") ?? "";
  const [scheme, token] = auth.split(" ");
  return scheme === "Bearer" && token ? token : null;
}

const PIN_PATTERN = /^\d{4,8}$/;

// Changing the PIN requires proving you know the current one first (which
// falls back to households.ts's documented default, 1003, for a household
// that hasn't set its own yet) — the same reason a phone or alarm panel
// asks for your existing passcode before letting you set a new one: the
// bearer token alone already gates who can reach this endpoint at all, but
// requiring the current PIN too means the PIN itself isn't just one
// request away from being silently swapped out by anything holding that
// token.
async function handleSetPin(request: Request, env: Env, householdId: string): Promise<Response> {
  let body: { current_pin?: string; new_pin?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.current_pin !== "string" || !PIN_PATTERN.test(body.current_pin)) {
    return jsonError("'current_pin' must be 4-8 digits", 400);
  }
  if (typeof body.new_pin !== "string" || !PIN_PATTERN.test(body.new_pin)) {
    return jsonError("'new_pin' must be 4-8 digits", 400);
  }

  if (!(await verifyHouseholdPin(env, householdId, body.current_pin))) {
    return jsonError("current_pin is incorrect", 401);
  }

  await setHouseholdPin(env, householdId, body.new_pin);
  return jsonOk({ ok: true });
}

// --- Integrator dashboard API ------------------------------------------------
//
// A separate auth domain from everything above: /integrator/* routes never
// check the household bearer token (extractBearerToken/resolveHousehold) —
// they authenticate via a signed session cookie instead (integrators.ts),
// set on signup/login. See docs/integrators.md.

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

async function handleIntegratorSignup(request: Request, env: Env): Promise<Response> {
  let body: { email?: string; password?: string; name?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.email !== "string" || !EMAIL_PATTERN.test(body.email)) {
    return jsonError("a valid 'email' is required", 400);
  }
  if (typeof body.password !== "string" || body.password.length < 8) {
    return jsonError("'password' must be at least 8 characters", 400);
  }

  let integrator;
  try {
    integrator = await createIntegrator(env, body.email, body.password, body.name);
  } catch {
    // The only way createIntegrator throws is a duplicate email — see
    // integrators.ts. Not distinguishing further errors here on purpose:
    // this response shouldn't leak database-shaped detail to a client.
    return jsonError("email already registered", 409);
  }

  return jsonOk({ integrator }, { "set-cookie": await createSessionCookie(env, integrator.id) });
}

async function handleIntegratorLogin(request: Request, env: Env): Promise<Response> {
  let body: { email?: string; password?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.email !== "string" || typeof body.password !== "string") {
    return jsonError("'email' and 'password' are required", 400);
  }

  const integrator = await verifyIntegratorLogin(env, body.email, body.password);
  if (!integrator) {
    return jsonError("invalid email or password", 401);
  }

  return jsonOk({ integrator }, { "set-cookie": await createSessionCookie(env, integrator.id) });
}

function handleIntegratorLogout(): Response {
  return jsonOk({ ok: true }, { "set-cookie": clearSessionCookie() });
}

async function handleListHouseholds(env: Env, integratorId: string): Promise<Response> {
  const households = await listIntegratorHouseholds(env, integratorId);
  return jsonOk({ households });
}

async function handleCreateHousehold(request: Request, env: Env, integratorId: string): Promise<Response> {
  let body: { name?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.name !== "string" || !body.name.trim()) {
    return jsonError("'name' is required", 400);
  }

  // Returns api_key in plaintext — the only time it's available that way,
  // same as any generated credential. The dashboard shows it once, at
  // creation; there's no way to read it back later (see households.ts).
  const household = await createHousehold(env, integratorId, body.name.trim());
  return jsonOk({ household });
}

/** Set (or clear) a household's own Home Assistant connection. Checks the
 * household actually belongs to this integrator first — otherwise one
 * integrator could point another's household at their own HA instance (or
 * anywhere else) just by guessing a household id. */
async function handleSetHouseholdHa(
  request: Request,
  env: Env,
  integratorId: string,
  householdId: string
): Promise<Response> {
  if (!(await householdBelongsToIntegrator(env, householdId, integratorId))) {
    return jsonError("not found", 404);
  }

  let body: { url?: string; token?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.url !== "string" || !/^https?:\/\//.test(body.url)) {
    return jsonError("a valid 'url' is required (including http(s)://)", 400);
  }
  if (typeof body.token !== "string" || !body.token) {
    return jsonError("'token' is required", 400);
  }

  try {
    await setHouseholdHaConfig(env, householdId, { url: body.url, token: body.token });
  } catch (err) {
    return jsonError(err instanceof Error ? err.message : "failed to save", 500);
  }

  return jsonOk({ ok: true });
}

/** Set (or clear) a household's heat pump optimization config — technical
 * setup, the same trust boundary as handleSetHouseholdHa above (an
 * integrator configuring a household they manage), not something a
 * homeowner enters. Whether this household is actually *billed* for
 * optimization to run is entirely separate — see heating_addon_active and
 * docs/billing.md; this only wires up the "how", not the "is paying". */
async function handleSetHouseholdEnergy(
  request: Request,
  env: Env,
  integratorId: string,
  householdId: string
): Promise<Response> {
  if (!(await householdBelongsToIntegrator(env, householdId, integratorId))) {
    return jsonError("not found", 404);
  }

  let body: {
    heatpump_entity_id?: string;
    room_temp_entity_id?: string;
    min_temp_c?: number;
    max_temp_c?: number;
    latitude?: string;
    longitude?: string;
    tariff_type?: string;
    octopus_region?: string;
    manual_default_pence?: number;
    manual_off_peak_windows?: { start?: string; end?: string; pence?: number }[];
  };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.heatpump_entity_id !== "string" || !body.heatpump_entity_id) {
    return jsonError("'heatpump_entity_id' is required", 400);
  }
  if (typeof body.room_temp_entity_id !== "string" || !body.room_temp_entity_id) {
    return jsonError("'room_temp_entity_id' is required", 400);
  }
  if (typeof body.min_temp_c !== "number" || typeof body.max_temp_c !== "number" || body.min_temp_c >= body.max_temp_c) {
    return jsonError("'min_temp_c' and 'max_temp_c' are required numbers, with min_temp_c < max_temp_c", 400);
  }
  if (typeof body.latitude !== "string" || typeof body.longitude !== "string" || !body.latitude || !body.longitude) {
    return jsonError("'latitude' and 'longitude' are required", 400);
  }

  // Octopus Agile's live pricing API, or a manually entered flat/time-of-use
  // schedule for every other supplier — see docs/energy.md for why there's
  // no live equivalent for them. Exactly one of the two shapes below.
  let tariff: HouseholdEnergyConfig["tariff"];
  if (body.tariff_type === "manual") {
    if (typeof body.manual_default_pence !== "number") {
      return jsonError("'manual_default_pence' is required when tariff_type is 'manual'", 400);
    }
    const windows = body.manual_off_peak_windows ?? [];
    if (!Array.isArray(windows) || !windows.every(isValidOffPeakWindow)) {
      return jsonError(
        "'manual_off_peak_windows' must be an array of { start: 'HH:MM', end: 'HH:MM', pence: number }",
        400
      );
    }
    tariff = { type: "manual", defaultPence: body.manual_default_pence, offPeakWindows: windows };
  } else if (!body.tariff_type || body.tariff_type === "octopus_agile") {
    if (typeof body.octopus_region !== "string" || !/^[A-P]$/.test(body.octopus_region)) {
      return jsonError("'octopus_region' must be a single letter A-P when tariff_type is 'octopus_agile'", 400);
    }
    tariff = { type: "octopus_agile", octopusRegion: body.octopus_region };
  } else {
    return jsonError("'tariff_type' must be 'octopus_agile' or 'manual'", 400);
  }

  await setHouseholdEnergyConfig(env, householdId, {
    heatpumpEntityId: body.heatpump_entity_id,
    roomTempEntityId: body.room_temp_entity_id,
    minTempC: body.min_temp_c,
    maxTempC: body.max_temp_c,
    metOfficeLatitude: body.latitude,
    metOfficeLongitude: body.longitude,
    tariff,
  });

  return jsonOk({ ok: true });
}

const HHMM_PATTERN = /^([01]\d|2[0-3]):[0-5]\d$/;

function isValidOffPeakWindow(w: { start?: string; end?: string; pence?: number }): w is OffPeakWindow {
  return (
    typeof w.start === "string" &&
    HHMM_PATTERN.test(w.start) &&
    typeof w.end === "string" &&
    HHMM_PATTERN.test(w.end) &&
    typeof w.pence === "number"
  );
}

// --- Customer billing portal API ---------------------------------------------
//
// A third, separate auth domain (customers.ts) — distinct from both the
// household bearer token above and the integrator session cookie. A
// homeowner claims their household with its existing api_key, then logs in
// with an email+password from then on. See docs/billing.md.

async function handlePortalSignup(request: Request, env: Env): Promise<Response> {
  let body: { api_key?: string; email?: string; password?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.api_key !== "string" || !body.api_key) {
    return jsonError("'api_key' is required", 400);
  }
  if (typeof body.email !== "string" || !EMAIL_PATTERN.test(body.email)) {
    return jsonError("a valid 'email' is required", 400);
  }
  if (typeof body.password !== "string" || body.password.length < 8) {
    return jsonError("'password' must be at least 8 characters", 400);
  }

  let customer;
  try {
    customer = await claimHousehold(env, body.api_key, body.email, body.password);
  } catch (err) {
    // claimHousehold's own errors are already client-safe (see customers.ts) —
    // just picking the right status code for each case here.
    const message = err instanceof Error ? err.message : "failed to set up account";
    return jsonError(message, message === "invalid API key" ? 401 : 409);
  }

  return jsonOk(
    { email: customer.email, subscription_status: null, heating_addon_active: false },
    { "set-cookie": await createCustomerSessionCookie(env, customer.householdId) }
  );
}

async function handlePortalLogin(request: Request, env: Env): Promise<Response> {
  let body: { email?: string; password?: string };
  try {
    body = await request.json();
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  if (typeof body.email !== "string" || typeof body.password !== "string") {
    return jsonError("'email' and 'password' are required", 400);
  }

  const customer = await verifyCustomerLogin(env, body.email, body.password);
  if (!customer) {
    return jsonError("invalid email or password", 401);
  }

  const billing = await getHouseholdBilling(env, customer.householdId);
  return jsonOk(
    {
      email: customer.email,
      subscription_status: billing?.subscriptionStatus ?? null,
      heating_addon_active: billing?.heatingAddonActive ?? false,
    },
    { "set-cookie": await createCustomerSessionCookie(env, customer.householdId) }
  );
}

function handlePortalLogout(): Response {
  return jsonOk({ ok: true }, { "set-cookie": clearCustomerSessionCookie() });
}

async function handlePortalStatus(env: Env, householdId: string): Promise<Response> {
  const billing = await getHouseholdBilling(env, householdId);
  return jsonOk({
    email: billing?.customerEmail ?? null,
    subscription_status: billing?.subscriptionStatus ?? null,
    heating_addon_active: billing?.heatingAddonActive ?? false,
  });
}

/** The Stripe publishable key, handed to the portal page so it can
 * initialize Stripe.js — deliberately unauthenticated, since publishable
 * keys are meant to be public (Stripe's own docs have them inline in
 * client-side JS). `null` when billing isn't configured yet; the page
 * shows a plain "not set up" message in that case rather than erroring. */
function handlePortalConfig(env: Env): Response {
  return jsonOk({ publishable_key: env.STRIPE_PUBLISHABLE_KEY ?? null });
}

/** Start (or restart) a household's subscription: ensures it has a Stripe
 * Customer, creates a Subscription in Stripe's "incomplete" flow (see
 * stripe.ts's createStripeSubscription for why) with the base assistant
 * price and, if requested, the heating optimization add-on price as a
 * second line item, and returns the first invoice's PaymentIntent
 * client_secret for the portal page to confirm with Stripe.js.
 * subscription_status/heating_addon_active only actually flip once that
 * confirmation succeeds and Stripe's webhook tells us so — not here. */
async function handlePortalStartSubscription(request: Request, env: Env, householdId: string): Promise<Response> {
  if (!env.STRIPE_SECRET_KEY || !env.STRIPE_CHAT_PRICE_ID) {
    return jsonError("billing is not configured on this Worker yet", 500);
  }

  let body: { include_heating?: boolean };
  try {
    body = await request.json();
  } catch {
    body = {};
  }
  const includeHeating = body.include_heating === true;
  if (includeHeating && !env.STRIPE_HEATING_PRICE_ID) {
    return jsonError("the heating optimization add-on is not configured on this Worker yet", 500);
  }

  const billing = await getHouseholdBilling(env, householdId);
  if (!billing?.customerEmail) {
    // Shouldn't happen — this route sits behind the customer session
    // cookie, which only exists for a claimed household — but fail
    // clearly rather than silently proceeding with no email on file.
    return jsonError("household has no billing account", 400);
  }

  try {
    let stripeCustomerId = billing.stripeCustomerId;
    if (!stripeCustomerId) {
      const customer = await createStripeCustomer(env.STRIPE_SECRET_KEY, billing.customerEmail, householdId);
      stripeCustomerId = customer.id;
      await setHouseholdStripeCustomer(env, householdId, stripeCustomerId);
    }

    const priceIds = includeHeating
      ? [env.STRIPE_CHAT_PRICE_ID, env.STRIPE_HEATING_PRICE_ID!]
      : [env.STRIPE_CHAT_PRICE_ID];
    const subscription = await createStripeSubscription(env.STRIPE_SECRET_KEY, stripeCustomerId, priceIds);
    await setHouseholdSubscription(env, householdId, subscription.id, subscription.status, includeHeating);

    const clientSecret = subscription.latest_invoice?.payment_intent?.client_secret;
    if (!clientSecret) {
      return jsonError("Stripe did not return a payment confirmation secret", 500);
    }

    return jsonOk({ client_secret: clientSecret });
  } catch (err) {
    return jsonError(err instanceof Error ? err.message : "failed to start subscription", 500);
  }
}

/** Stripe webhook receiver — the only way subscription_status ever changes
 * after the initial POST /portal/billing/start-subscription write, since
 * that call only knows the subscription's *initial* state ("incomplete"),
 * not whether the customer's card was actually charged successfully.
 * Authenticated by Stripe's own signature scheme (stripe.ts's
 * verifyStripeWebhookSignature), not a bearer token or session cookie —
 * Stripe is the caller, not a browser. */
async function handleBillingWebhook(request: Request, env: Env): Promise<Response> {
  if (!env.STRIPE_WEBHOOK_SECRET) {
    return jsonError("STRIPE_WEBHOOK_SECRET is not configured on this Worker", 500);
  }

  // Must read as raw text before anything else touches the body — the
  // signature is computed over these exact bytes (see stripe.ts).
  const rawBody = await request.text();
  const valid = await verifyStripeWebhookSignature(
    rawBody,
    request.headers.get("stripe-signature"),
    env.STRIPE_WEBHOOK_SECRET
  );
  if (!valid) {
    return jsonError("invalid signature", 400);
  }

  let event: { type?: string; data?: { object?: Record<string, unknown> } };
  try {
    event = JSON.parse(rawBody);
  } catch {
    return jsonError("invalid JSON body", 400);
  }

  const eventType = event.type ?? "";
  const obj = event.data?.object ?? {};

  // customer.subscription.{created,updated,deleted} carry the full
  // subscription object — id, status, customer, and its line items (each
  // with a price.id) all present directly, which is how heating_addon_active
  // gets kept in sync: true iff the heating price is actually one of this
  // subscription's items right now. A .deleted event forces it false
  // outright rather than trusting items (the subscription's gone either
  // way) — belt and braces alongside listHouseholdsReadyForEnergyOptimization's
  // own subscription_status check.
  if (eventType.startsWith("customer.subscription.")) {
    const subscriptionId = obj["id"] as string | undefined;
    const status = obj["status"] as string | undefined;
    const customerId = obj["customer"] as string | undefined;
    const items = obj["items"] as { data?: { price?: { id?: string } }[] } | undefined;
    const heatingAddonActive =
      eventType === "customer.subscription.deleted"
        ? false
        : (items?.data ?? []).some((item) => item.price?.id === env.STRIPE_HEATING_PRICE_ID);

    if (subscriptionId && status) {
      const household = customerId ? await findHouseholdByStripeCustomerId(env, customerId) : null;
      if (household) {
        await setHouseholdSubscription(env, household.id, subscriptionId, status, heatingAddonActive);
      } else {
        await updateSubscriptionAddonsBySubscriptionId(env, subscriptionId, status, heatingAddonActive);
      }
    }
  }

  // Invoice events are the clearest, fastest signal for the two statuses
  // that actually matter for chat.ts's gate — handled explicitly rather
  // than waiting on the subscription.updated event Stripe sends alongside
  // them, which can arrive in either order.
  if (eventType === "invoice.payment_succeeded" || eventType === "invoice.payment_failed") {
    const subscriptionId = obj["subscription"] as string | undefined;
    if (subscriptionId) {
      await updateSubscriptionStatusBySubscriptionId(
        env,
        subscriptionId,
        eventType === "invoice.payment_succeeded" ? "active" : "past_due"
      );
    }
  }

  return jsonOk({ received: true });
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Browsers send this before the real cross-origin request (a
    // "preflight") to ask permission — no auth, no body, just headers.
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    // Unauthenticated demo chat page — just markup, the API key the page
    // asks for is only ever used client-side to call /chat directly, which
    // still enforces the real auth check below. Lets ROSE be demoed from
    // any browser (e.g. a phone) by opening this Worker's own URL.
    if (url.pathname === "/" && request.method === "GET") {
      return new Response(CHAT_UI_HTML, {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }

    // Unauthenticated integrator dashboard page — same idea as the chat page
    // above: just markup, served same-origin so it can call /integrator/*
    // with a relative path and have the browser handle the session cookie.
    // No auth at the route level; the page itself shows login/signup until
    // /integrator/households proves there's a valid session.
    if (url.pathname === "/dashboard" && request.method === "GET") {
      return new Response(DASHBOARD_HTML, {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }

    // Unauthenticated customer billing portal page — same idea, for
    // homeowners rather than integrators. See docs/billing.md.
    if (url.pathname === "/portal" && request.method === "GET") {
      return new Response(BILLING_UI_HTML, {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }

    // Unauthenticated health check, useful for the HA config flow's
    // "test connection" step and for uptime monitoring.
    if (url.pathname === "/health") {
      return withCors(
        new Response(JSON.stringify({ status: "ok" }), {
          headers: { "content-type": "application/json" },
        })
      );
    }

    // Stripe webhook — server-to-server, no cookie or bearer token; verified
    // via the Stripe-Signature header instead (stripe.ts). Checked here,
    // ahead of every auth gate below, same as /health.
    if (url.pathname === "/billing/webhook" && request.method === "POST") {
      return withCors(await handleBillingWebhook(request, env));
    }

    // Integrator dashboard API — a separate auth domain from the household
    // bearer-token routes below, so this is checked and handled entirely
    // before that gate. Signup/login are unauthenticated by nature (that's
    // what they establish); every other /integrator/* route requires a
    // valid session cookie (see integrators.ts).
    if (url.pathname.startsWith("/integrator")) {
      // Every integrator route needs this to sign/verify session cookies —
      // fail with a clear error now rather than an unhandled exception deep
      // in integrators.ts, which would surface as Cloudflare's generic
      // error page (no CORS headers, "failed to fetch" client-side) instead
      // of a real error message.
      if (!env.SESSION_SECRET) {
        return withCors(jsonError("SESSION_SECRET is not configured on this Worker", 500));
      }

      if (url.pathname === "/integrator/signup" && request.method === "POST") {
        return withCors(await handleIntegratorSignup(request, env));
      }
      if (url.pathname === "/integrator/login" && request.method === "POST") {
        return withCors(await handleIntegratorLogin(request, env));
      }
      if (url.pathname === "/integrator/logout" && request.method === "POST") {
        return withCors(handleIntegratorLogout());
      }

      const integratorId = await verifySessionCookie(env, extractSessionCookie(request));
      if (!integratorId) {
        return withCors(unauthorized());
      }

      if (url.pathname === "/integrator/households" && request.method === "GET") {
        return withCors(await handleListHouseholds(env, integratorId));
      }
      if (url.pathname === "/integrator/households" && request.method === "POST") {
        return withCors(await handleCreateHousehold(request, env, integratorId));
      }

      const haMatch = url.pathname.match(/^\/integrator\/households\/([^/]+)\/ha$/);
      if (haMatch && request.method === "POST") {
        return withCors(await handleSetHouseholdHa(request, env, integratorId, haMatch[1]));
      }

      const energyMatch = url.pathname.match(/^\/integrator\/households\/([^/]+)\/energy$/);
      if (energyMatch && request.method === "POST") {
        return withCors(await handleSetHouseholdEnergy(request, env, integratorId, energyMatch[1]));
      }

      return withCors(jsonError("not found", 404));
    }

    // Customer billing portal API — a third auth domain (customers.ts),
    // separate from both the household bearer token below and the
    // integrator session cookie above. /portal/config is deliberately
    // unauthenticated (see handlePortalConfig); signup/login establish the
    // session, everything else after them requires it.
    if (url.pathname.startsWith("/portal/")) {
      if (!env.SESSION_SECRET) {
        return withCors(jsonError("SESSION_SECRET is not configured on this Worker", 500));
      }

      if (url.pathname === "/portal/config") {
        return withCors(handlePortalConfig(env));
      }
      if (url.pathname === "/portal/signup" && request.method === "POST") {
        return withCors(await handlePortalSignup(request, env));
      }
      if (url.pathname === "/portal/login" && request.method === "POST") {
        return withCors(await handlePortalLogin(request, env));
      }
      if (url.pathname === "/portal/logout" && request.method === "POST") {
        return withCors(handlePortalLogout());
      }

      const customerHouseholdId = await verifyCustomerSessionCookie(env, extractCustomerSessionCookie(request));
      if (!customerHouseholdId) {
        return withCors(unauthorized());
      }

      if (url.pathname === "/portal/status" && request.method === "GET") {
        return withCors(await handlePortalStatus(env, customerHouseholdId));
      }
      if (url.pathname === "/portal/billing/start-subscription" && request.method === "POST") {
        return withCors(await handlePortalStartSubscription(request, env, customerHouseholdId));
      }

      return withCors(jsonError("not found", 404));
    }

    const token = extractBearerToken(request);
    const household = token ? await resolveHousehold(env, token) : null;
    if (!household) {
      return withCors(unauthorized());
    }

    if (url.pathname === "/chat" && request.method === "POST") {
      // Only a household that *engaged* billing and then lapsed is blocked
      // here — a household with no subscription at all (subscription_status
      // is null: every household today, until docs/billing.md's flow is
      // used) is unaffected, same as before this existed. See migration
      // 0007's comment.
      if (household.subscription_status === "past_due" || household.subscription_status === "canceled") {
        return withCors(
          jsonError("subscription payment is past due — resolve it at /portal before ROSE can respond", 402)
        );
      }
      return withCors(await handleChat(request, env, ctx, household.id));
    }

    // Sets the household's admin PIN (chat.ts's HIGH_RISK_SERVICES gate) —
    // deliberately a separate, non-conversational endpoint rather than
    // something ROSE itself can do from a chat message. Letting the PIN be
    // set or changed through the same self-reported-identity conversation
    // path it's meant to add a check *beyond* would defeat the purpose.
    // Gated only by the household's own bearer token, same as /chat.
    if (url.pathname === "/admin/pin" && request.method === "POST") {
      return withCors(await handleSetPin(request, env, household.id));
    }

    // Energy optimization — see docs/energy.md and docs/billing.md. Gated
    // by the household's own bearer token, same as /chat, and a no-op
    // unless ENERGY_OPTIMIZATION_ENABLED="true"; POST /energy/run also
    // requires the household to be both technically configured (its
    // integrator's job — see handleSetHouseholdEnergy) and either the
    // bootstrap 'default' household or actually paying for the add-on,
    // same condition households.ts's listHouseholdsReadyForEnergyOptimization
    // uses for the cron.
    if (url.pathname === "/energy/status" && request.method === "GET") {
      return withCors(await handleEnergyStatus(env, household.id));
    }

    if (url.pathname === "/energy/run" && request.method === "POST") {
      const energyConfig = await getHouseholdEnergyConfig(env, household.id);
      if (!energyConfig) {
        return withCors(
          jsonError("heating optimization isn't set up for this household yet — ask your installer", 409)
        );
      }
      if (household.id !== "default") {
        const billing = await getHouseholdBilling(env, household.id);
        const active =
          billing?.heatingAddonActive &&
          (billing.subscriptionStatus === "active" || billing.subscriptionStatus === "trialing");
        if (!active) {
          return withCors(
            jsonError("the heating optimization add-on isn't active for this household — subscribe at /portal", 402)
          );
        }
      }
      return withCors(await handleEnergyRun(env, household.id, energyConfig));
    }

    return withCors(jsonError("not found", 404));
  },

  // Cloudflare Cron Trigger (see wrangler.jsonc `triggers.crons`) — recomputes
  // every eligible household's heating plan and applies the current slot's
  // target temperature, plus the (still global, 'default'-only) solar/EV
  // cycle. No-op unless ENERGY_OPTIMIZATION_ENABLED="true" — see
  // docs/energy.md. The two run independently (one failing doesn't block
  // the other) since they're now genuinely separate concerns.
  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    if (env.ENERGY_OPTIMIZATION_ENABLED !== "true") return;
    ctx.waitUntil(
      runAllHeatPumpOptimizations(env).catch((err) => console.error("scheduled heat pump optimization failed", err))
    );
    ctx.waitUntil(
      runSolarAndEvOptimization(env).catch((err) => console.error("scheduled solar/EV optimization failed", err))
    );
  },
} satisfies ExportedHandler<Env>;
